/* Showing All data of 3 tables */
SELECT WP.ER_CODE, EP.ER_NAME, EP.PROV AS PROVINCE_NAME, WP.NOC_CNP AS NOC_CODE, NOC.NOC_TITLE, WP.LOW_WAGE, WP.HIGH_WAGE, WP.MEDIAN_WAGE, WP.AVERAGE_WAGE, DS.DATA_SOURCE_NAME, WP.REFERENCE_PERIOD, WP.REVISION_DATE
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
INNER JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
INNER JOIN DATA_SOURCE DS ON WP.DATA_SOURCE_ID = DS.DATA_SOURCE_ID
ORDER BY WP.ER_CODE

/* To find out the lowest wage per hour as province. */
SELECT EP.PROV, MIN(WP.LOW_WAGE) AS LOWEST_WAGE_PER_PROVINCE
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY EP. PROV
ORDER BY MIN(WP.LOW_WAGE) ASC

/* Find out maximum wage rate per hour per province. */
SELECT EP.PROV, MAX(WP.HIGH_WAGE) AS HIGHEST_WAGE_PER_PROVINCE
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY EP. PROV
ORDER BY MAX(WP.HIGH_WAGE) DESC

/* Find out lowest wages as per economic region.*/
SELECT EP.ER_NAME, EP.PROV, MIN(WP.LOW_WAGE) AS LOWEST_WAGE_PER_ER
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY EP.ER_NAME, EP.PROV
ORDER BY MIN(WP.LOW_WAGE) ASC


/* Find out highest wages as per economic region.*/
SELECT EP.ER_NAME, EP.PROV, MAX(WP.HIGH_WAGE) AS HIGHEST_WAGE_PER_ER
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY EP.ER_NAME, EP.PROV
ORDER BY MAX(WP.HIGH_WAGE) DESC

/* To find out top 15 NOC title earns the highest wage per hour. */
SELECT NOC.NOC_TITLE, EP.PROV AS PROVINCE, MAX(WP.HIGH_WAGE) AS HIGHEST_WAGE_AS_PER_NOC_TITLE
FROM WAGE_PER_PROVINCE WP
INNER JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY NOC.NOC_TITLE, EP.PROV
ORDER BY MAX(WP.HIGH_WAGE) DESC
LIMIT 15

/* To find the lowest 5 wage as per noc title in a province. */
SELECT NOC.NOC_TITLE, EP.PROV AS PROVINCE, MIN(WP.LOW_WAGE) AS LOWEST_WAGE_AS_PER_NOC_TITLE
FROM WAGE_PER_PROVINCE WP
INNER JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY NOC.NOC_TITLE, EP.PROV
ORDER BY MIN(WP.LOW_WAGE) ASC
LIMIT 5

/* To COUNT economic region that has median wage above CAD45.00 */
SELECT EP.ER_CODE, EP.ER_NAME, COUNT(WP.MEDIAN_WAGE) AS COUNT_OF_MEDIAN_WAGE_ABOVE_$45
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
WHERE WP.MEDIAN_WAGE >= 45.00
GROUP BY EP.ER_CODE, EP.ER_NAME
ORDER BY COUNT_OF_MEDIAN_WAGE_ABOVE_$45 DESC

/* To COUNT economic region has average wage above 50.00 */
SELECT EP.ER_CODE, EP.ER_NAME, COUNT(WP.AVERAGE_WAGE) AS COUNT_OF_AVERAGE_WAGE_ABOVE_$50
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
WHERE WP.AVERAGE_WAGE >= 50.00
GROUP BY EP.ER_CODE, EP.ER_NAME
ORDER BY COUNT_OF_AVERAGE_WAGE_ABOVE_$50 DESC

/* Display the TOP 10 noc titles with the most difference in the hourly wages. */
SELECT NOC.NOC_TITLE, WP.LOW_WAGE, WP.HIGH_WAGE, 
WP.HIGH_WAGE - WP.LOW_WAGE AS DIFFERENCE_IN_HIGH_LOW_WAGE
FROM WAGE_PER_PROVINCE WP
JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
GROUP BY NOC.NOC_TITLE, WP.HIGH_WAGE, WP.LOW_WAGE
ORDER BY DIFFERENCE_IN_HIGH_LOW_WAGE DESC
LIMIT 10


/* Display province wise wages rate -average low wage, average high wage, average median wage, average of avg wage */
SELECT EP.PROV, AVG(WP.LOW_WAGE) AS AVG_LOW_WAGE, AVG(WP.HIGH_WAGE) AS AVG_HIGH_WAGE, AVG(WP.MEDIAN_WAGE) AS AVG_MEDIAN_WAGE, AVG(WP.AVERAGE_WAGE) AS AVG_AVG_WAGE
FROM WAGE_PER_PROVINCE WP
JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
GROUP BY EP.PROV
ORDER BY EP.PROV

/* Showing NOC data as per data source */
SELECT WP.NOC_CNP, NOC.NOC_TITLE, DS.DATA_SOURCE_NAME
FROM WAGE_PER_PROVINCE WP
INNER JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
INNER JOIN DATA_SOURCE DS ON WP.DATA_SOURCE_ID = DS.DATA_SOURCE_ID
GROUP BY WP.NOC_CNP, NOC.NOC_TITLE, DS.DATA_SOURCE_NAME
ORDER BY DS.DATA_SOURCE_NAME


/* Views */
CREATE OR REPLACE VIEW ALL_DETAILS AS 
SELECT WP.ER_CODE, EP.ER_NAME, EP.PROV AS PROVINCE_NAME, WP.NOC_CNP AS NOC_CODE, NOC.NOC_TITLE, WP.LOW_WAGE, WP.HIGH_WAGE, WP.MEDIAN_WAGE, WP.AVERAGE_WAGE, DS.DATA_SOURCE_NAME, WP.REFERENCE_PERIOD, WP.REVISION_DATE
FROM WAGE_PER_PROVINCE WP
INNER JOIN ER_PER_PROVINCE EP ON WP.ER_CODE = EP.ER_CODE
INNER JOIN NOC ON WP.NOC_CNP = NOC.NOC_CNP
INNER JOIN DATA_SOURCE DS ON WP.DATA_SOURCE_ID = DS.DATA_SOURCE_ID
ORDER BY WP.ER_CODE

